sudo: required
services:
- docker
before_install:
- docker build -t lucasazambuja/docker-react -f Dockerfile.dev .
script:
- docker run -e CI=true lucasazambuja/docker-react npm run test
deploy:
  edge: true
  provider: elasticbeanstalk
  access_key_id:
    secure: VdF5jFM1xD5KbDTRpLCjwZ/hDvBBQLrP3PlZKlOefHuz/y1gqQjzfARkpFPyDnn6G+33HwQ5A875nnVQcKfQlI9utCbvbfonizplQe/8VSlLUppUE5ACgJGn35JnrvS8YikzVlXGcG3bax0sKMRGLeWHI/1eu/Urm7glkOz8X1vqhvuTimWeydBnZR05Cxy9b5wDEdiXLOTzHERbSmMDPtZGGjWZ4FQc3sTjWdIJhNso0lYjUoNM4YsKDNHXsjFIItxMVGNQssdZ+vPaSGOr0vlO9Ujp4x36VbhMhAqUgsA/y91AAY3yBCHuNXMAtojEVA3TK3rcb43XKWkzF569hNTorO+qdxfEgqUPP+OroxTSc+GxBqs7Zg9YGKwLmMO/twsCTDtR29spCeSAMXxKLqCMXhSCif6M1ayQXPe3Tiq8pbLYFI/pc+2o3EdNSPL9BqxlVVgOqTPD66P4BWCOAWvgQ2KX8mYg2ehkN+FAFSs054eThHkXDTHUWdE4JuDJ0FOhfejppPv954F/t+GGr1+iHRog+qnYqXccD6D3uPg+WmIlGOMJ5yzSV5vcL2vQNNzqJMplRXraTGRiAfQ0Dj0vXvosddDQV2ouFMpLaDdHjROU9+zpNY0NbVXMZwzGDB6zFQ8R1Tzu8tKyGK/3AocQ/ZcxbIuI899y7Pp66LQ=
  secret_access_key:
    secure: T5KBELfK/MQWA3WAHymdNNPh8iEVixMuTYTLte57gDAW0vhvQoGYp2nVVP7IeDrc6TV6MnZL3uWzEw7ZVKPhBm+X1KLJX0i+djh7uRS2iSBbzjvxGGCy8hqpgJxozCYSUKmudo+vr3LkC/glvcx7v+sQ9bskrVRJPF8spZECJk0hoFfquKVQccRGUVxql8FqRjqeUh/6BfFxlTzUeokDu8Ns1JOR3YwyQ98kj8A8AE3PpCT0tsHR27Ule2xijvNuaVgWIJs5r9Lx2usE8/Nh3ijJb9us0vjG6KwNgytJoV8g9/KA6x0jEpmCXkWrTfjkIo2AF30Nnhpho5ZVAPvy/e+5Ly5514jwoCiHNv6QnSPO830LVvab+3a7mzwSBuHEhd8IHseKruje69zk5p3SbdkiIl1mkN+A1NtuulwHQarJFfoLybg6nzXz2h2Okr8KrTyAU31s9GEfaNWm4ngebnOphr56cGMlOAsuszPVdP9YJIf9nlwsu8QkSV2gzV2yFIFbb5u/PyIYiaznjV/0z5vsjohhylWHEKK+WTaJwNwPuHjnPuv7bOk6c/XCR9TcLZEpGu4Dxye5RsEO7pJE1cN6pqDihWHkxX+Vg7F1E68UxX8mTcV+qgX7pTcaIy6b6ikw4ZZRz50yfM1raNUKbvokpDkWnc9FoXGH9UjsLos=
  region: sa-east-1
  bucket_name: elasticbeanstalk-sa-east-1-028953928914
  bucket_path: DOCKER
  app: DOCKER
  env: docker-react-3
  on:
    branch: master
